**KNN**

In [19]:
from sklearn import preprocessing
import pandas as pd
import numpy as np


In [20]:
from sklearn.neighbors import KNeighborsClassifier

df = pd.read_csv("knn.csv")

print(df)

   X  Y Class
0  2  4     N
1  4  6     N
2  4  4     P
3  4  2     N
4  6  4     N
5  6  2     P


In [42]:
# features
x = df.iloc[:,:-1].values
print("\n",x)

# class labels
y = df.iloc[:,2].values
print("\n",y)


 [[2 4]
 [4 6]
 [4 4]
 [4 2]
 [6 4]
 [6 2]]

 ['N' 'N' 'P' 'N' 'N' 'P']


In [22]:
# for k=3
classifier = KNeighborsClassifier(n_neighbors = 3)

# train
classifier.fit(x,y)
x_test = np.array([4,2])

# test
y_pred = classifier.predict([x_test])
print(y_pred)

['P']


In [41]:
# assigning features and label variables

# 1st feature
weather = ['Sunny','Sunny','Overcast','Rainy','Rainy','Rainy','Overcast','Sunny','Sunny','Rainy','Sunny','Overcast','Overcast','Rainy']
# 2nd feature
temp = ['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild','Cool','Mild','Mild','Mild','Hot','Mild']

# target or label variable
play = ['No','No','Yes','Yes','Yes','No','Yes','No','Yes','Yes','Yes','Yes','Yes','No']

le = preprocessing.LabelEncoder()

# encoding to numbers
weather_enc = le.fit_transform(weather)
temp_enc = le.fit_transform(temp)
label_enc = le.fit_transform(play)

print("\n",weather_enc)
print("\n",temp_enc)
print("\n",label_enc)


 [2 2 0 1 1 1 0 2 2 1 2 0 0 1]

 [1 1 1 2 0 0 0 2 0 2 2 2 1 2]

 [0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [26]:
# combine weather and temp in a single list of tuples

features = list(zip(weather_enc,temp_enc))
features

[(2, 1),
 (2, 1),
 (0, 1),
 (1, 2),
 (1, 0),
 (1, 0),
 (0, 0),
 (2, 2),
 (2, 0),
 (1, 2),
 (2, 2),
 (0, 2),
 (0, 1),
 (1, 2)]

In [27]:
# for k=3
model = KNeighborsClassifier(n_neighbors = 3)

# train
model.fit(features,label_enc)
x_test = np.array([0,2])

# test
pred = model.predict([x_test])
print(pred)


[1]


In [30]:
# import csv
df1 = pd.read_csv("knn1.csv")

print(df1)

   Height  Age  Weight
0    5.00   45      77
1    5.11   26      47
2    5.60   30      55
3    5.90   34      59
4    4.80   40      72
5    5.80   36      60
6    5.30   19      40
7    5.80   28      60
8    5.50   23      45
9    5.60   32      58


In [45]:
# features
x1 = df1.iloc[:,:-1].values
print("\n",x1)

# class labels
y1 = df1.iloc[:,2].values
print("\n",y1)


 [[ 5.   45.  ]
 [ 5.11 26.  ]
 [ 5.6  30.  ]
 [ 5.9  34.  ]
 [ 4.8  40.  ]
 [ 5.8  36.  ]
 [ 5.3  19.  ]
 [ 5.8  28.  ]
 [ 5.5  23.  ]
 [ 5.6  32.  ]]

 [77 47 55 59 72 60 40 60 45 58]


In [32]:
# for k=3
classifier3 = KNeighborsClassifier(n_neighbors = 3)

# train
classifier3.fit(x1,y1)
x1_test = np.array([5.50,26])

# test
y1_pred = classifier3.predict([x1_test])
print(y1_pred)

[45]


In [33]:
# for k=4
classifier4 = KNeighborsClassifier(n_neighbors = 4)

# train
classifier4.fit(x1,y1)
x1_test = np.array([5.50,26])

# test
y1_pred = classifier4.predict([x1_test])
print(y1_pred)

[45]


In [34]:
# for k=5
classifier5 = KNeighborsClassifier(n_neighbors = 5)

# train
classifier5.fit(x1,y1)
x1_test = np.array([5.50,26])

# test
y1_pred = classifier5.predict([x1_test])
print(y1_pred)

[45]


In [35]:
# import KNN regressor
from sklearn.neighbors import KNeighborsRegressor

# for k=5
classifier = KNeighborsRegressor(n_neighbors = 5)

# train
classifier.fit(x1,y1)
x1_test = np.array([5.50,26])

# test
y1_pred = classifier.predict([x1_test])
print(y1_pred)

[53.]


In [44]:
from sklearn import datasets

wine = datasets.load_wine()

# print feature names
print("\n",wine.feature_names)

# print label species
print("\n",wine.target_names)


 ['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']

 ['class_0' 'class_1' 'class_2']


In [43]:
# print wine labels  (0:class_0,1:class_1,2:class_2)
print("\n",wine.target)


 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
